# Usa una imagen oficial de PHP con Apache
FROM php:8.1-apache

# Copia los archivos de tu proyecto al contenedor
COPY . /var/www/html/

# Otorga permisos a los archivos
RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html

# Habilita extensiones adicionales si son necesarias
RUN docker-php-ext-install mysqli

# Expón el puerto 80 para el servidor web
EXPOSE 80
